### **What is numpy?**
NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types.

### **Numpy Arrays Vs Python Sequences**

- NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

- The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

- NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

- A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.

### Basic Revision

In [ ]:
age = int(input('Enter the age : '))

if age >= 18:
  print('You are adult')
else:
  print('You are minor')

Enter the age : 45
You are adult


In [ ]:
for i in range(1,6):
  print('Iteration :',i)

Iteration : 1
Iteration : 2
Iteration : 3
Iteration : 4
Iteration : 5


## Creating Numpy Arrays

In [2]:
# Creating Numpy
# np.array

import numpy as np

b = np.array([1,2,3])

a = np.array([1,2,3,4,5])
print(a)
print(b)
print(type(a))

[1 2 3 4 5]
[1 2 3]
<class 'numpy.ndarray'>


In [3]:
np.array([1,3,4])
a = np.array([1,3,5])
print(a)

[1 3 5]


In [4]:
# 2D array

a = np.array([[1,2,3],[4,5,6]])
print('First 2D array' , a)

b = np.array([[12,23,12],[20,40,60]])
print('Second 2D array : ', b)

First 2D array [[1 2 3]
 [4 5 6]]
Second 2D array :  [[12 23 12]
 [20 40 60]]


In [8]:
# dtype function
# np.array([],dtype = float/bool/complex...)

a = np.array([1,2,3],dtype = float)
print(a)
b = np.array([1,2,3],dtype = bool)
print(b)
c = np.array([1,2,3],dtype = complex)
print(c)

[1. 2. 3.]
[ True  True  True]
[1.+0.j 2.+0.j 3.+0.j]


In [12]:
# np.arange()

a = np.arange(1,11)
print(a)

b = np.arange(1,11,2)
print(b)

[ 1  2  3  4  5  6  7  8  9 10]
[1 3 5 7 9]


In [22]:
# reshape
a = np.arange(1,11).reshape(2,5)
print(a)

b = np.arange(1,11).reshape(5,2)
print(b)

c = np.arange(1,13).reshape(3,4)
print(c)

d = np.arange(16).reshape(2,2,2,2)
print(d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [28]:
# np.ones and # np.zeroes -> This function is used for creating the vector or
# matrix of only ones or zeroes

# Basically,this function is used to initialised the vector or matrix with one & zero
a = np.ones((3,4))
print("Matrix Having only ones : ", a)

b = np.zeros((4,5))
print("Matrix Having only zeroes : ", b)

c = np.ones((1,5))
print("Vector Having initial value 1 : ", c)

Matrix Having only ones :  [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Matrix Having only zeroes :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Vector Having initial value 1 :  [[1. 1. 1. 1. 1.]]


In [30]:
# np.random() -> This is used to initialised matrix or vector with random number b/w 0-1

a = np.random.random((3,4))
print(a)

[[0.98343718 0.95555058 0.38866037 0.38930804]
 [0.61386598 0.20205277 0.0533476  0.81009453]
 [0.3969536  0.75680846 0.38471836 0.88632382]]


In [33]:
# np.linspace() -> linearly space function() means it generate the equi distance point b/w the range

#   np.linspace(start,end,no_of_points)

a = np.linspace(-10,10,10)
print(a)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [34]:
# np.identity() -> identity matrix whose diagonal matrix is 1 where as all is 0

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Array Attributes

In [42]:
a1 = np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print(a2)
print(a3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]
[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [43]:
# ndim -> numpy attribute which is used to find the dimension of numpy.

print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
3


In [47]:
# shape -> it returns the shape of vector/matrix
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2)


In [49]:
# size -> no. of items in the vector/matrix

print(a1.size)
print(a2.size)
print(a3.size)

10
12
8


In [54]:
# itemsize -> it gives the size of each item in memory

print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

# itemsize of int32 is 4 bits
b1 = np.arange(1,11,dtype=np.int32)
print(b1)
print(b1.itemsize)

8
8
8
[ 1  2  3  4  5  6  7  8  9 10]
4


In [55]:
# dtype -> gives the data type of the matrix/vector

print(a1.dtype)
print(a2.dtype)
print(a3.dtype)
print(b1.dtype)

int64
float64
int64
int32


### Changing Datatype
